FROM node:16.20.0 as builder

COPY repos/react-example /opt/frontend

RUN cd /opt/frontend && \
  yarn && \
  yarn build

FROM nginxinc/nginx-unprivileged:1.24.0-bullseye-perl as frontend

COPY --from=builder --chown=101:101 /opt/frontend/build /usr/share/nginx/html
COPY --chown=101:101 react-web/nginx.conf /etc/nginx/conf.d/default.conf
