name: Build Latest Image

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: clone app
        uses: actions/checkout@v3
        with:
          repository: react-example
          # ssh-key: ${{ secrets.CI_REACT_EXAMPLE_SSH }}
          path: repos/react-example
          ref: main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/bake-action@v2
        with:
          push: true
          no-cache: true
          files: docker-bake-web-latest.hcl
